export default {
  CREATE_INGREDIENT: 'CREATE_INGREDIENT',
  LOAD_INGREDIENT_SUCCESS: 'LOAD_INGREDIENT_SUCCESS',
  SAVE_INGREDIENT_SUCCESS: 'SAVE_INGREDIENT_SUCCESS',
  DELETE_INGREDIENT_SUCCESS: 'DELETE_INGREDIENT_SUCCESS',
  UPDATE_INGREDIENT_SUCCESS: 'UPDATE_INGREDIENT_SUCCESS',
  LOAD_RECIPES_SUCCESS: 'LOAD_RECIPES_SUCCESS',
  DELETE_RECIPE_SUCCESS: 'DELETE_RECIPE_SUCCESS',
  ADD_RECIPE_SUCCESS: 'ADD_RECIPE_SUCCESS',
  UPDATE_RECIPE_SUCCESS: 'UPDATE_RECIPE_SUCCESS'
};
